deezer/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("callback/", views.callback, name="callback"),
    path("playlists/", views.playlists, name="playlists"),
    path("duplicates/", views.duplicates, name="duplicates"),
]

playlist_manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("deezer/", include("deezer.urls"), name="deezer"),
    path("admin/", admin.site.urls),
]

deezer/models.py
from django.db import models
from django.db.models import Count


class Track(models.Model):
    title = models.CharField(max_length=255)
    link = models.URLField()

    def __str__(self) -> str:
        return self.title


class Playlist(models.Model):
    title = models.CharField(max_length=255)
    tracks = models.ManyToManyField(Track)
    link = models.URLField()

    def __str__(self) -> str:
        return self.title


def find_multiplaylist_tracks() -> list[Track]:
    return list(
        Track.objects.annotate(playlist_count=Count("playlist")).filter(
            playlist_count__gt=1
        )
    )

deezer/views.py
import requests
from django.conf import settings
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render

from deezer.models import Playlist, find_multiplaylist_tracks


def index(request):
    return render(request, "deezer/index.html")


def login(request: HttpRequest):
    context = {
        "DEEZER_APP_ID": settings.DEEZER_APP_ID,
        "DEEZER_CALLBACK_URL": settings.DEEZER_CALLBACK_URL,
    }
    return render(request, "deezer/login.html", context)


def callback(request: HttpRequest):
    code = request.GET.get("code")

    params = {
        "app_id": settings.DEEZER_APP_ID,
        "secret": settings.DEEZER_SECRET_KEY,
        "code": code,
        "output": "json",
    }
    token_link = "https://connect.deezer.com/oauth/access_token.php"
    token_response = requests.get(token_link, params, timeout=5)
    token_json = token_response.json()

    response = HttpResponseRedirect("/deezer/")
    response.set_cookie(
        "deezer_access_token",
        token_json["access_token"],
        max_age=token_json["expires"],
    )
    return response


def playlists(request: HttpRequest):
    context = {"playlists": Playlist.objects.all()}
    return render(request, "deezer/playlists.html", context)


def duplicates(request: HttpRequest):
    tracks = find_multiplaylist_tracks()
    context = {"tracks": tracks}
    return render(request, "deezer/duplicates.html", context)

deezer/templates/deezer/duplicates.html
{% include "deezer/header.html" %}
<h1>Duplicates</h1>
<ul>
    {% for track in tracks %}
        <li>
            <a href="{{ track.link }}">{{ track.title }}</a>
            <ul>
                {% for playlist in track.playlist_set.all %}
                    <li>
                        <a href="{{ playlist.link }}">{{ playlist.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>

deezer/templates/deezer/header.html
<h1>Header</h1>
<ul>
    <li>
        <a href="{% url 'index' %}">Start</a>
    </li>
    <li>
        <a href="{% url 'login' %}">Login</a>
    </li>
    <li>
        <a href="{% url 'playlists' %}">Playlists</a>
    </li>
    <li>
        <a href="{% url 'duplicates' %}">Duplicates</a>
    </li>
</ul>

deezer/templates/deezer/index.html
{% include "deezer/header.html" %}

deezer/templates/deezer/login.html
{% include "deezer/header.html" %}
<h1>
    <a href="https://connect.deezer.com/oauth/auth.php?app_id={{ DEEZER_APP_ID }}&redirect_uri={{ DEEZER_CALLBACK_URL }}">🔗 Login</a>
</h1>

deezer/templates/deezer/playlists.html
{% include "deezer/header.html" %}
<h1>Playlists</h1>
<ul>
    {% for playlist in playlists %}
        <li>
            <a href="{{ playlist.link }}">{{ playlist.title }}</a>
        </li>
    {% endfor %}
</ul>